import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";
import { Link } from "wouter";

export default function Terms() {
  return (
    <div className="min-h-screen bg-background">
      <div className="container max-w-4xl mx-auto px-4 py-8">
        <Link href="/">
          <Button variant="ghost" className="mb-6" data-testid="button-back-home">
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Home
          </Button>
        </Link>

        <Card>
          <CardHeader>
            <CardTitle className="text-3xl">Terms of Service</CardTitle>
            <p className="text-muted-foreground">Last updated: January 24, 2026</p>
          </CardHeader>
          <CardContent className="prose prose-sm dark:prose-invert max-w-none space-y-6">
            <section>
              <h2 className="text-xl font-semibold mb-3">1. Acceptance of Terms</h2>
              <p className="text-muted-foreground">
                By accessing and using BrightBoard ("the Service"), you agree to be bound by these Terms of Service. 
                If you do not agree to these terms, please do not use our Service.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">2. Description of Service</h2>
              <p className="text-muted-foreground">
                BrightBoard is an AI-powered content creation platform designed for educators. Our Service allows 
                teachers to generate educational content including images, presentations, worksheets, activities, 
                storyboards, and text content using artificial intelligence.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">3. User Accounts</h2>
              <p className="text-muted-foreground">
                To access certain features of the Service, you must create an account. You are responsible for:
              </p>
              <ul className="list-disc list-inside text-muted-foreground mt-2 space-y-1">
                <li>Maintaining the confidentiality of your account credentials</li>
                <li>All activities that occur under your account</li>
                <li>Notifying us immediately of any unauthorized use</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">4. Subscription and Payments</h2>
              <p className="text-muted-foreground">
                BrightBoard offers both free and paid subscription tiers. Paid subscriptions are processed through 
                our payment provider, Paddle. By subscribing to a paid plan, you agree to:
              </p>
              <ul className="list-disc list-inside text-muted-foreground mt-2 space-y-1">
                <li>Pay the applicable subscription fees</li>
                <li>Automatic renewal unless cancelled before the renewal date</li>
                <li>Paddle's terms of service for payment processing</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">5. Acceptable Use</h2>
              <p className="text-muted-foreground">
                You agree not to use the Service to:
              </p>
              <ul className="list-disc list-inside text-muted-foreground mt-2 space-y-1">
                <li>Generate content that is illegal, harmful, or inappropriate for educational settings</li>
                <li>Violate any applicable laws or regulations</li>
                <li>Infringe on intellectual property rights of others</li>
                <li>Attempt to circumvent usage limits or security measures</li>
                <li>Share account credentials with unauthorized users</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">6. Intellectual Property</h2>
              <p className="text-muted-foreground">
                Content you generate using BrightBoard is yours to use for educational purposes. However, 
                the BrightBoard platform, including its design, features, and underlying technology, remains 
                our intellectual property.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">7. AI-Generated Content</h2>
              <p className="text-muted-foreground">
                Content generated by our AI is provided "as is." While we strive for accuracy and appropriateness, 
                you are responsible for reviewing all generated content before use in educational settings. 
                We do not guarantee that AI-generated content will be error-free or suitable for all purposes.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">8. Limitation of Liability</h2>
              <p className="text-muted-foreground">
                To the maximum extent permitted by law, BrightBoard shall not be liable for any indirect, 
                incidental, special, consequential, or punitive damages resulting from your use of the Service.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">9. Changes to Terms</h2>
              <p className="text-muted-foreground">
                We reserve the right to modify these Terms at any time. We will notify users of significant 
                changes via email or through the Service. Continued use after changes constitutes acceptance 
                of the modified Terms.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">10. Contact Information</h2>
              <p className="text-muted-foreground">
                For questions about these Terms, please contact us at: support@brightboardapp.com
              </p>
            </section>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
